In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("trade_bgd.csv")
df

,Country Name,Country ISO3,Year,Indicator Name,Indicator Code,Value
0,#country+name,#country+code,#date+year,#indicator+name,#indicator+code,#indicator+value+num
1,Bangladesh,BGD,2022,Trade in services (% of GDP),BG.GSR.NFSV.GD.ZS,4.43835293707687
2,Bangladesh,BGD,2021,Trade in services (% of GDP),BG.GSR.NFSV.GD.ZS,4.40597975973846
3,Bangladesh,BGD,2020,Trade in services (% of GDP),BG.GSR.NFSV.GD.ZS,3.72997148965385
4,Bangladesh,BGD,2019,Trade in services (% of GDP),BG.GSR.NFSV.GD.ZS,4.49026337741122
...,...,...,...,...,...,...
5135,Bangladesh,BGD,1980,Travel services (% of commercial service exports),TX.VAL.TRVL.ZS.WT,9.24506007426596
5136,Bangladesh,BGD,1979,Travel services (% of commercial service exports),TX.VAL.TRVL.ZS.WT,9.96272868771304
5137,Bangladesh,BGD,1978,Travel services (% of commercial service exports),TX.VAL.TRVL.ZS.WT,7.53036311138536
5138,Bangladesh,BGD,1977,Travel services (% of commercial service exports),TX.VAL.TRVL.ZS.WT,9.93896159742711
5139,Bangladesh,BGD,1976,Travel services (% of commercial service exports),TX.VAL.TRVL.ZS.WT,7.52546834215148